rules:
  use-trusted-publishing:
    ignore:
      - release.yml:60:9
  unpinned-uses:
    ignore: []
    config:
      policies:
        actions/*: ref-pin
        pypa/gh-action-pypi-publish: ref-pin
        codecov/codecov-action: ref-pin
