language: python
dist: xenial

python:
- '3.6'
- '3.7'
- '3.8'

env:
- DJANGO_VERSION=2.2.*
- DJANGO_VERSION=3.0.*
- DJANGO_VERSION=3.1.*

script:
- pip install codecov
- pip install -q django==$DJANGO_VERSION
- pip install -e '.[test]'
- coverage run setup.py test
- coverage report -m --fail-under=85
- flake8
- isort --check .

after_success:
- codecov

deploy:
  provider: pypi
  user: kingbuzzman
  skip_existing: true
  password:
    secure: b/fGwqup8JZVHWKlYTWR7E7sQvXnKMKfczbuEtMnNjbUo8Zfh1JX6OPW0K+DH/WiA4gmXryK7f9BJhCR9tXbkVZUWki856/8zsIkoOvXXkoIIXx/2ZmGmCbQ1yyvN70U+DmabopLfj6jypp5lr6JOV/hLPtpJtmN+/dfU69/3wgslOP5Qvj1j3Ii+RA6BfKglCewgFdVK5PAHbb5iT44yNv+TRBOWNKcsLSaSwITTW3bLxfMVe08QbZvpKoDH5bOrgi/X/wOtpY++ceFuIhOtjwVGwM6rDEKpmchedTEPkTNlflwtd7xzsYkOAxRQOLRI88/TEIKjPFtti2Fwmfe7rQ3L7rozrY7mMvbIvZPpoxZRl2KLMHsu+7fJxEJQ3Xgqf1IMjwB0btQDjakO/+oOlGO3Xe41zCiB23YRZJjl5y1yaOZcrCNTvTBWODmjpmrf/2vWOn/YVPz0R8V9UaJRwTZJ+JaxTKFeRGBm4MEXEvyBzQTlMux0wWW59v1uYaOa7ZHzKy2O/GvpTyqj6ZVhf1LiTMZNRAA/JbZdhZ3jA+jNrYTyvvyXjNqQugazNIsb6cl5LrOCLPNmBLTnp5F39C6Tg2gREE4YYGaUbow+O4yoSggkb3bW7klsAMsnTkZRt9cCYsmKpdYzblcinzfhc4Z5gXYgrLtrp5R287mFro=
  on:
    branch: master
