# Generated by Django 3.2.22 on 2023-10-13 10:38

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("unicode_name", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-score"], name="message_e_score_385f90_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["unicode_name"], name="message_e_unicode_6789fc_gin"
            ),
        ),
    ]
