# Generated by Django 2.0 on 2019-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'),
                ('app', '0002_person_age')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
