# Generated by Django 2.0 on 2019-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
