# Generated by Django 2.0 on 2019-05-18 15:22

from django.db import migrations
from django.db.migrations import RunPython


def same_name(apps, schema_editor):
    # original function
    return


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(same_name, migrations.RunPython.noop),
        migrations.RunPython(RunPython.noop, migrations.RunPython.noop),
    ]
