# Generated by Django 2.0 on 2019-05-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_add_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="Address",
            name="city",
            field=models.CharField(max_length=50, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="Address",
            name="postal_code",
            field=models.CharField(max_length=50, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="Address",
            name="province",
            field=models.CharField(max_length=50, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="Address",
            name="country",
            field=models.CharField(max_length=50, default=""),
            preserve_default=False,
        ),
    ]
