name: Test Include

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  DEFAULT_PYTHON_VERSION: 3.13

jobs:
  prepare-matrix:
    name: Prepare Python/Django matrix
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install the linters
        run: |
          pip install uv
          uv pip install --system --upgrade setuptools toml
          # Note that we don't install .[lint] becuase we don't want to install "this" pakage + lint. We ONLY want to install the "lint"
          uv pip install --system $(python -c 'import toml; print(" ".join(toml.load(open("pyproject.toml"))["project"]["optional-dependencies"]["lint"]))')
      - name: Generate matrix
        run: |
          python -c '
          import toml
          import json
          import os

          DJANGO_VERSIONS = []
          PYTHON_VERSIONS = []
          EXCLUDE_MATRIX = {"3.9": ["5.0.*", "5.1.*", "5.2.*", "main"], "3.10": ["5.2.*", "main"], "3.11": ["5.2.*", "main"]}

          def is_number(s):
              try:
                  float(s)
                  return True
              except ValueError:
                  return False

          with open("pyproject.toml") as f:
              conf = toml.load(f)
          for classifier in conf["project"]["classifiers"]:
              if "Framework :: Django ::" in classifier:
                  version = classifier.split("::")[-1].strip()
                  if "." in version and is_number(version):
                      DJANGO_VERSIONS.append(version)
              elif "Programming Language :: Python ::" in classifier:
                  version = classifier.split("::")[-1].strip()
                  if "." in version and is_number(version):
                      PYTHON_VERSIONS.append(version)

          matrix = {
              "python-version": PYTHON_VERSIONS,
              "django-version": [f"{v}.*" for v in DJANGO_VERSIONS] + ["main"],
              "exclude": [{"python-version": p, "django-version": d} for p, djs in EXCLUDE_MATRIX.items() for d in djs],
          }

          with open(os.getenv("GITHUB_ENV"), "a") as env_file:
              pretty = " ".join(DJANGO_VERSIONS)
              env_file.write(f"django={pretty}\n")
              pretty = " ".join(PYTHON_VERSIONS)
              env_file.write(f"python={pretty}\n")
              env_file.write(f"matrix={json.dumps(matrix)}\n")
          '
      - name: Check version EOF
        id: set-matrix
        run: |
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          python -c "
          import os
          import json
          from urllib.request import Request, urlopen
          from datetime import date, datetime, timedelta

          DJANGO_VERSIONS = os.getenv('django').split()
          PYTHON_VERSIONS = os.getenv('python').split()

          today = date.today()
          WARNING_DAYS = timedelta(days=90)
          version_by_product = {
              'django': DJANGO_VERSIONS,
              'python': PYTHON_VERSIONS
          }
          for product, supported_versions in version_by_product.items():
              url = f'https://endoflife.date/api/{product}.json'
              with urlopen(Request(url)) as response:
                  data = json.loads(response.read())
              for detail in data:
                  version = detail['cycle']
                  eol = detail['eol']
                  eol_date = datetime.strptime(eol, '%Y-%m-%d').date()
                  if version not in supported_versions:
                      if eol_date > today:
                          print(f'::error ::{product} v{version}: is not in the supported versions list')
                      continue
                  if eol_date < today:
                      print(f'::error ::{product} v{version}: EOL was {eol}')
                  elif eol_date - today < WARNING_DAYS:
                      print(f'::warning ::{product} v{version}: EOL is coming up on the {eol}')
          "
      - name: Ruff check
        if: always()
        run: |
          ruff check --extend-select I .
          ruff format --check .
      - name: Vulture check
        if: always()
        run: |
          vulture
      - name: rst check
        if: always()
        run: rst-lint .
      - name: Zizmor
        run: find .github/workflows -name '*.yml' | xargs zizmor --config .github/zizmor.yml
      - name: Continue
        if: always()
        run: exit 0

  tests:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    name: Python ${{ matrix.python-version }} - Django ${{ matrix.django-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.python-version }}-dj-${{ matrix.django-version }}
      - name: Install prerequisites
        run: |
          echo ARTIFACT_NAME=coverage_${{ runner.os }}-py-${MATRIX_PYTHON_VERSION}-dj-${MATRIX_DJANGO_VERSION} | sed 's|\.\*||g' >> "$GITHUB_ENV"
          DJANGO="django==${MATRIX_DJANGO_VERSION}"
          if [[ "${MATRIX_DJANGO_VERSION}" == "main" ]]; then
            DJANGO="git+https://github.com/django/django.git@main"
          fi
          pip install uv
          uv pip install --system --upgrade setuptools codecov-cli $DJANGO
        env:
          MATRIX_PYTHON_VERSION: ${{ matrix.python-version }}
          MATRIX_DJANGO_VERSION: ${{ matrix.django-version }}
      - name: Install packages
        run: uv pip install --system -e '.[test]'
      - name: Run tests
        id: pytest
        continue-on-error: true
        run: |
          python -m coverage run -m pytest
          coverage combine
          coverage report --show-missing
        env:
          # PYTHONWARNINGS is a comma-separated list of warning filters.
          # 1. "error": Treat all warnings as errors by default.
          # 2. "ignore...django-squash": Ignore a known internal warning from django-squash.
          # 3. "ignore...USE_L10N": Ignore deprecation warning for compatibility with older Django versions.
          # 4. "ignore...LegacyVersion": Ignore a deprecation warning from a dependency creating a LegacyVersion.
          PYTHONWARNINGS: "error,ignore:Django migrations writer file has changed and may not be compatible with django-squash,ignore:The USE_L10N setting is deprecated:,ignore:Creating a LegacyVersion has been deprecated"
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          if-no-files-found: error
          name: ${{ env.ARTIFACT_NAME }}
          path: .coverage
          retention-days: 1
      - name: Validate run
        run: |
          if [ "${STEPS_PYTEST_OUTCOME}" != "success" ]; then
            echo "Tests failed!"
            exit 1
          fi
        env:
          STEPS_PYTEST_OUTCOME: ${{ steps.pytest.outcome }}

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    name: Coverage
    if: success() || failure()
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install coverage
        run: pip install coverage diff-cover
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded_artifacts
      - name: Clean up temporary artifacts
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b  # v5.1.0
        with:
          name: coverage_*
      - name: Combine coverage.py
        run: |
          coverage combine $(find downloaded_artifacts/ -type f | xargs)
          # Used by codecov
          coverage xml
      - name: Upload single coverage artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          if-no-files-found: error
          name: .coverage
          path: .coverage
          retention-days: 1
      - name: Diff coverage
        run: |
          diff-cover coverage.xml --compare-branch origin/master --format github-annotations:warning
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        continue-on-error: true
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,RUST
      - name: Check
        run: coverage report --format=markdown --fail-under=90 >> $GITHUB_STEP_SUMMARY
