name: Tests

on:
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - master

jobs:
  django-squash:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        django-version:
        - '2.2.*'
        - '3.2.*'
        - '4.0.*'
        exclude:
        - { django-version: '4.0.*', python-version: '3.7' }
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install prerequisites
      run: python -m pip install --upgrade pip setuptools codecov pip install codecov django==${{ matrix.django-version }}
    - name: Install packages
      run: pip install -e '.[test]'
    - name: Run tests
      run: coverage run setup.py test
    - name: Coverage check
      run: coverage report -m --fail-under=85
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: .coverage
    - name: Flake8 check
      run: flake8
    - name: iSort check
      run: isort --check .
