name: CI

concurrency:
  group: django-squash-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

permissions:
  contents: read

jobs:
  django-squash:
    name: Tests
    uses: ./.github/workflows/_tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      ref: ${{ github.ref }}
