name: Tests

concurrency:
  group: django-squash-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

jobs:
  django-squash:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        django-version:
          - "3.2.*"
          - "4.1.*"
          - "4.2.*"
        exclude:
          - { django-version: "4.1.*", python-version: "3.7" }
          - { django-version: "4.2.*", python-version: "3.7" }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install prerequisites
        run: python -m pip install --upgrade pip setuptools codecov pip install codecov django==${{ matrix.django-version }}
      - name: Install packages
        run: pip install -e '.[test]'
      - name: Run tests
        run: coverage run setup.py test
      - name: Coverage check
        run: coverage report -m --fail-under=85
      - name: Coverage XML
        run: coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
      - name: Flake8 check
        run: flake8
      - name: iSort check
        run: isort --check .
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.head_ref, 'master')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
